apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: es
build:
  artifacts:
  - image: ar4mirez/say-what-es
  local: {}
deploy:
  kustomize:
    paths:
    - ./k8s
test:
- image: ar4mirez/say-what-es
  structureTests:
  - './structure-test/no-go-binary.yaml'
  - './structure-test/compiled-binary.yaml'
