apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: develop
namePrefix: es-

commonLabels:
  app: es
  env: develop

bases:
- ../../manifests/base/http

images:
- name: http
  newName: ar4mirez/say-what-es
