apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deploy.yaml
- service.yaml

configMapGenerator:
- name: configmap
  files:
  - configmap.conf

secretGenerator:
- name: secrets
  files:
  - secrets.env
